# Generated by Django 4.0.2 on 2023-04-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('fundacja', 'Fundacja'), ('organizacja_pozarzadowa', 'Organizacja pozarządowa'), ('zbiorka_lokalna', 'Zbiórka lokalna')], default='fundacja', max_length=30)),
                ('categories', models.ManyToManyField(to='charity.Category')),
            ],
        ),
    ]
