# Generated by Django 4.0.2 on 2023-05-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0003_donation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'permissions': [('can_manage_institutions', 'Can manage institutions')]},
        ),
        migrations.RemoveField(
            model_name='donation',
            name='pick_up_time',
        ),
        migrations.AddField(
            model_name='donation',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
    ]
