# Generated by Django 4.0.2 on 2023-05-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0004_alter_institution_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='pick_up_time',
            field=models.TimeField(null=True),
        ),
    ]
